#!/bin/bash

# Get the process ID (PID) of 4-to_infinity_and_beyond
pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    # Kill the process using SIGTERM
    kill "$pid"
    echo "Terminated"
else
    echo "Process not found"
fi

