#!/usr/bin/env bash
# This script tells the story of users in /etc/passwd using the while loop + IFS

# Using a while loop to read lines from /etc/passwd
while IFS=':' read -r username _ uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd

