#!/usr/bin/env bash
# This script connects to a server using SSH with a private key

# Connect to the server using the private key ~/.ssh/school
ssh -i ~/.ssh/school ubuntu@8.8.8.8

# Print a message and exit
echo "Connection to 8.8.8.8 closed."

